//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quaer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quaer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The profile folder was not found. After opening the browser, enter all the necessary confidential information for further operation of the program..
        /// </summary>
        public static string ChromeHelper_Check {
            get {
                return ResourceManager.GetString("ChromeHelper_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chrome Version:.
        /// </summary>
        public static string ChromeHelper_Version {
            get {
                return ResourceManager.GetString("ChromeHelper_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Dialog_Error {
            get {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Dialog_Info {
            get {
                return ResourceManager.GetString("Dialog_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text files.
        /// </summary>
        public static string Dialog_Txt {
            get {
                return ResourceManager.GetString("Dialog_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Dialog_Warning {
            get {
                return ResourceManager.GetString("Dialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MW_About {
            get {
                return ResourceManager.GetString("MW_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Queries Automata
        ///Version 1.0
        ///Copyright (c) 2020 Vladimir Kovalev
        ///Licensed under MIT License.
        /// </summary>
        public static string MW_AboutInfo {
            get {
                return ResourceManager.GetString("MW_AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After closing the program, the list of results will be cleared. Continue?.
        /// </summary>
        public static string MW_ConfimQuit {
            get {
                return ResourceManager.GetString("MW_ConfimQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create web driver.
        /// </summary>
        public static string MW_CreateDriver {
            get {
                return ResourceManager.GetString("MW_CreateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit profile.
        /// </summary>
        public static string MW_EditProfile {
            get {
                return ResourceManager.GetString("MW_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Engines.
        /// </summary>
        public static string MW_Engines {
            get {
                return ResourceManager.GetString("MW_Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Queries Automata.
        /// </summary>
        public static string MW_Header {
            get {
                return ResourceManager.GetString("MW_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string MW_Help {
            get {
                return ResourceManager.GetString("MW_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string MW_Menu {
            get {
                return ResourceManager.GetString("MW_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load new queries.
        /// </summary>
        public static string MW_OpenQueries {
            get {
                return ResourceManager.GetString("MW_OpenQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string MW_Quit {
            get {
                return ResourceManager.GetString("MW_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save current queries.
        /// </summary>
        public static string MW_SaveQueries {
            get {
                return ResourceManager.GetString("MW_SaveQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save results.
        /// </summary>
        public static string MW_SaveResults {
            get {
                return ResourceManager.GetString("MW_SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close web driver.
        /// </summary>
        public static string MW_ShutdownDriver {
            get {
                return ResourceManager.GetString("MW_ShutdownDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queries.
        /// </summary>
        public static string QV_Header {
            get {
                return ResourceManager.GetString("QV_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string RV_ButtonClear {
            get {
                return ResourceManager.GetString("RV_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string RV_ButtonSave {
            get {
                return ResourceManager.GetString("RV_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string RV_ButtonStart {
            get {
                return ResourceManager.GetString("RV_ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string RV_ButtonStop {
            get {
                return ResourceManager.GetString("RV_ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear results?.
        /// </summary>
        public static string RV_ClearResults {
            get {
                return ResourceManager.GetString("RV_ClearResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link.
        /// </summary>
        public static string RV_ColumnLink {
            get {
                return ResourceManager.GetString("RV_ColumnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Query.
        /// </summary>
        public static string RV_ColumnQuery {
            get {
                return ResourceManager.GetString("RV_ColumnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string RV_ColumnTitle {
            get {
                return ResourceManager.GetString("RV_ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results.
        /// </summary>
        public static string RV_Header {
            get {
                return ResourceManager.GetString("RV_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to Clipboard.
        /// </summary>
        public static string RV_MenuCopy {
            get {
                return ResourceManager.GetString("RV_MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in Browser.
        /// </summary>
        public static string RV_MenuOpen {
            get {
                return ResourceManager.GetString("RV_MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove from list.
        /// </summary>
        public static string RV_MenuRemove {
            get {
                return ResourceManager.GetString("RV_MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queries list is empty!.
        /// </summary>
        public static string RV_QueriesEmpty {
            get {
                return ResourceManager.GetString("RV_QueriesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is empty!.
        /// </summary>
        public static string Scraping_FileEmpty {
            get {
                return ResourceManager.GetString("Scraping_FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing:.
        /// </summary>
        public static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation aborted.
        /// </summary>
        public static string Status_StopAll {
            get {
                return ResourceManager.GetString("Status_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total:.
        /// </summary>
        public static string Status_Total {
            get {
                return ResourceManager.GetString("Status_Total", resourceCulture);
            }
        }
    }
}
